version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - common-network

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    networks:
      - common-network

  matcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-matcher
    environment:
      APP_NAME: 'counter-service in docker'
      IN_DOCKER: "true"
      PSQL_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      DRAGONFLY_URL: dragonfly:6379
    ports:
      - "8081:8081"
    depends_on:
      - dragonfly
      - postgres
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
